# Generated by Django 5.2.7 on 2025-11-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendationlog',
            name='chosen_food',
        ),
        migrations.RemoveField(
            model_name='recommendationlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='QuestionnaireResponse',
        ),
        migrations.DeleteModel(
            name='RecommendationLog',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
