# Generated by Django 5.2.7 on 2025-11-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_questionnaireresponse_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='course',
        ),
        migrations.RemoveField(
            model_name='food',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='food',
            name='popularity',
        ),
        migrations.AddField(
            model_name='food',
            name='recipe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
