# Generated by Django 5.2.7 on 2025-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_food_id_food_ingredients_alter_food_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='recipe_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
